### ISSUE TITLE
Installation failure with included modules. gsl required

### ISSUE THREAD

**Issue by jason-neal** [nespinoza/exonailer#1]
Hi there,
I had trouble installing exonailer because of the automatic installation of the external modules. The failed with exit code 1 was not very helpful to work out why it failed.

(azores)) [jneal@localhost exonailer]$ python install.py  
    > Numpy is ok!
     > Scipy is ok!
     > Astropy is ok!
     > batman is ok!
     > emcee is ok!
     > C code found in directory utilities/ajplanet. Building...
     ----------------------------------------------------------
     > ERROR: exonailer couldn't be installed.
     > Problem building code in utilities/ajplanet. The error was:

```
    error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./ -I/usr/local/include -Ibuild/src.linux-x86_64-2.7 -I/home/jneal/miniconda3/envs/azores/lib/python2.7/site-packages/numpy/core/include -I/home/jneal/miniconda3/envs/azores/include/python2.7 -c ./true_anomaly.c -o build/temp.linux-x86_64-2.7/true_anomaly.o" failed with exit status 1
```

After trying to build ajplanet manually I recovered this error.

((azores)) [jneal@localhost ajplanet]$ make
gcc -c true_anomaly.c -I/usr/local/include
true_anomaly.c:3:25: fatal error: gsl/gsl_math.h: No such file or directory
compilation terminated.
Makefile:19: recipe for target 'true_anomaly.o' failed
make: **\* [true_anomaly.o] Error 1

Which revealed that I was missing the GNU scientific library (gsl).

It would be helpful if gsl was added to the requirements list. Or that the error message could return the error message from ajplanet which would have easily shown that gsl was missing.

Thanks Jason

**Comment by nespinoza** [comment]
Hi Jason,

 Thanks a lot for your message. I'll add GSL to the things to check for in the next update of the code,

Best
