### ISSUE TITLE
FWT?

### ISSUE THREAD

**Issue by ridlo** [nespinoza/exonailer#2]
> Traceback (most recent call last):
>   File "exonailer.py", line 5, in <module>
>     import data_utils
>   File "utilities/data_utils.py", line 195, in <module>
>     import Wavelets
>   File "utilities/Wavelets.py", line 3, in <module>
>     import FWT
> ImportError: No module named FWT

What is FWT module? is it from GSL? 
I already install gsl in my Ubuntu 16.04 using "sudo apt-get install libgsl2 libgsl-dev"

**Comment by nespinoza** [comment]
Hi @ridlo,
 Thanks for using exonailer! FWT is a C code that performs a fast wavelet transform. This should be automatically installed once you run the "install.py" script. It is possible it failed for some reason for you?

Best,
Néstor

**Comment by ridlo** [comment]
Ok, thank you. I think I forgot to run that after installing GSL.
