### ISSUE TITLE
unused urllib import on install.py

### ISSUE THREAD

**Issue by martinberoiz** [nespinoza/exonailer#3]
Hi, 

I noticed you import `urllib` and `tarfile` on `install.py` but it's never used. Do you think you can remove them?

Also, would you be interested in a pull request with a distutils-type installation with a setup.py?
That way installation would go as

    python setup.py install

**Comment by nespinoza** [comment]
Hi @martinberoiz! Just removed them, thanks for the suggestion. Regarding a distutils-type installation, it would be great! 

Thanks in advance

Best

Néstor
